// frontend/src/pages/DeviceDetailPage.tsx
import { useEffect, useMemo, useState } from "react";
import {
  fetchAlarmList,
  fetchDevices,
  fetchWatchlist,
  pinWatchlistDevice,
  unpinWatchlistDevice,
  updateAlarmStatus,
} from "../api/backend";
import type {
  AlarmListItem,
  AlarmStatus,
  DeviceData,
  WatchlistItem,
} from "../api/backend";
import type { RouteMatch } from "../types/route";
import DeviceDetailPanel from "../components/DeviceDetailPanel";

export default function DeviceDetailPage({ route, onNavigate }: { route: RouteMatch; onNavigate: (target: string) => void }) {
  const [allDevicesData, setAllDevicesData] = useState<DeviceData[]>([]);
  const [errorMessage, setErrorMessage] = useState("");
  const [keyword, setKeyword] = useState("");
  const [selectedStatus, setSelectedStatus] = useState<"" | DeviceData["status"]>("");
  const [watchList, setWatchList] = useState<WatchlistItem[]>([]);
  const [currentDeviceCode, setCurrentDeviceCode] = useState("");
  const [alarmItems, setAlarmItems] = useState<AlarmListItem[]>([]);
  const [alarmStatus, setAlarmStatus] = useState<AlarmStatus>("new");
  const [alarmLoading, setAlarmLoading] = useState(false);
  const [alarmErrorMessage, setAlarmErrorMessage] = useState("");
  const [alarmUpdatingId, setAlarmUpdatingId] = useState<number | null>(null);

  const alarmTabs: Array<{ label: string; value: AlarmStatus }> = [
    { label: "新告警", value: "new" },
    { label: "已确认", value: "acknowledged" },
    { label: "已解决", value: "resolved" },
  ];

  const watchSet = useMemo(() => new Set(watchList.map((item) => item.deviceCode)), [watchList]);

  const filteredDevices = useMemo(() => {
    const normalizedKeyword = keyword.toLowerCase();
    return allDevicesData.filter((device) => {
      const keywordMatched =
        normalizedKeyword.length === 0 ||
        device.name.toLowerCase().includes(normalizedKeyword) ||
        device.deviceCode.toLowerCase().includes(normalizedKeyword);
      const statusMatched = selectedStatus === "" || device.status === selectedStatus;
      return keywordMatched && statusMatched;
    });
  }, [allDevicesData, keyword, selectedStatus]);

  const currentDevice = useMemo(
    () => allDevicesData.find((device) => device.deviceCode === currentDeviceCode),
    [allDevicesData, currentDeviceCode]
  );
  const notFound = Boolean(currentDeviceCode) && !currentDevice && allDevicesData.length > 0;

  const syncRouteState = () => {
    const routeCode = route.path === "/devices/:deviceCode" ? route.params.deviceCode || "" : "";
    setCurrentDeviceCode(routeCode);
    const keywordFromQuery = route.query.get("keyword");
    if (keywordFromQuery !== null) {
      setKeyword(keywordFromQuery);
    }
  };

  const loadAlarmItems = async (deviceCode: string, status: AlarmStatus) => {
    if (!deviceCode) {
      setAlarmItems([]);
      return;
    }
    try {
      setAlarmLoading(true);
      setAlarmItems(await fetchAlarmList(status, 20, deviceCode));
      setAlarmErrorMessage("");
    } catch (error) {
      setAlarmErrorMessage(`告警数据加载失败: ${error instanceof Error ? error.message : String(error)}`);
    } finally {
      setAlarmLoading(false);
    }
  };

  useEffect(() => {
    syncRouteState();
  }, [route.path, route.params.deviceCode, route.query]);

  useEffect(() => {
    const loadPage = async () => {
      try {
        const devices = await fetchDevices();
        setAllDevicesData(devices);
        setWatchList(await fetchWatchlist());
        setErrorMessage("");
      } catch (error) {
        setErrorMessage(`设备数据加载失败: ${error instanceof Error ? error.message : String(error)}`);
      }
    };
    void loadPage();
  }, []);

  useEffect(() => {
    void loadAlarmItems(currentDeviceCode, alarmStatus);
  }, [currentDeviceCode, alarmStatus]);

  useEffect(() => {
    if (!currentDeviceCode && filteredDevices.length > 0) {
      setCurrentDeviceCode(filteredDevices[0].deviceCode);
    }
  }, [currentDeviceCode, filteredDevices]);

  return (
    <div className="device-page">
      <div className="page-header">
        <div className="title">设备列表与详情</div>
        <div className="subtitle">搜索、关注并快速进入单设备详情</div>
      </div>

      <div className="filter-bar">
        <input
          value={keyword}
          onChange={(event) => setKeyword(event.target.value)}
          className="filter-input"
          type="text"
          placeholder="搜索设备名称或 deviceCode"
        />
        <select value={selectedStatus} onChange={(event) => setSelectedStatus(event.target.value as "" | DeviceData["status"])} className="filter-select">
          <option value="">全部状态</option>
          <option value="normal">normal</option>
          <option value="warning">warning</option>
          <option value="error">error</option>
        </select>
        <button
          className="clear-btn"
          onClick={() => {
            setKeyword("");
            setSelectedStatus("");
          }}
        >
          清空筛选
        </button>
        <span className="filter-count">
          显示 {filteredDevices.length} / {allDevicesData.length}
        </span>
      </div>

      {errorMessage ? <div className="status-message error">{errorMessage}</div> : null}
      {!errorMessage && allDevicesData.length === 0 ? <div className="status-message">暂无设备数据</div> : null}
      {!errorMessage && allDevicesData.length > 0 ? (
        <div className="device-layout">
          <div className="list-panel">
            <div className="list-title">设备列表</div>
            {filteredDevices.length === 0 ? <div className="status-message">筛选结果为空，请调整条件</div> : null}
            {filteredDevices.map((device) => (
              <div
                key={device.deviceCode}
                className={`list-item ${currentDevice?.deviceCode === device.deviceCode ? "active" : ""}`.trim()}
              >
                <div className="list-item-main" onClick={() => onNavigate(`/devices/${encodeURIComponent(device.deviceCode)}`)}>
                  <div className="name">{device.name}</div>
                  <div className="meta">
                    {device.deviceCode} · {device.status}
                  </div>
                </div>
                <button
                  className="pin-btn"
                  onClick={async () => {
                    if (watchSet.has(device.deviceCode)) {
                      setWatchList(await unpinWatchlistDevice(device.deviceCode));
                      return;
                    }
                    setWatchList(await pinWatchlistDevice(device.deviceCode));
                  }}
                >
                  {watchSet.has(device.deviceCode) ? "取消关注" : "关注"}
                </button>
              </div>
            ))}
          </div>

          <div className="watch-panel">
            <div className="list-title">关注列表</div>
            {watchList.length === 0 ? <div className="empty-watch">暂无关注设备</div> : null}
            {watchList.map((item) => (
              <div
                key={item.deviceCode}
                className="watch-item"
                onClick={() => onNavigate(`/devices/${encodeURIComponent(item.deviceCode)}`)}
              >
                {item.deviceCode}
              </div>
            ))}
          </div>

          <div className="detail-panel">
            {notFound ? (
              <div className="status-message error">
                未找到设备 {route.params.deviceCode}，请从左侧列表重新选择。
              </div>
            ) : null}
            {!notFound && currentDevice ? (
              <div className="detail-with-alarm-actions">
                <DeviceDetailPanel deviceData={currentDevice} embedded onClose={() => onNavigate("/devices")} />
                <div className="alarm-ops-panel">
                  <div className="list-title">告警操作（设备列表执行）</div>
                  <div className="alarm-tabs">
                    {alarmTabs.map((tab) => (
                      <button
                        key={tab.value}
                        className={`alarm-tab-btn ${alarmStatus === tab.value ? "active" : ""}`.trim()}
                        onClick={() => {
                          if (alarmStatus !== tab.value && !alarmLoading) {
                            setAlarmStatus(tab.value);
                          }
                        }}
                      >
                        {tab.label}
                      </button>
                    ))}
                  </div>
                  {alarmErrorMessage ? <div className="status-message error">{alarmErrorMessage}</div> : null}
                  {!alarmErrorMessage && alarmLoading ? <div className="status-message">告警数据加载中...</div> : null}
                  {!alarmErrorMessage && !alarmLoading && alarmItems.length === 0 ? (
                    <div className="status-message">当前筛选下暂无告警</div>
                  ) : null}
                  {!alarmErrorMessage && !alarmLoading && alarmItems.length > 0 ? (
                    <div className="alarm-ops-list">
                      {alarmItems.map((alarm) => (
                        <div key={alarm.id} className="alarm-ops-item">
                          <div className="alarm-ops-main">
                            <div className="alarm-ops-event">{alarm.event}</div>
                            <div className="alarm-ops-meta">
                              {alarm.time} · {alarm.status}
                            </div>
                          </div>
                          {alarm.status === "new" ? (
                            <button
                              className="alarm-action-btn"
                              disabled={alarmUpdatingId === alarm.id}
                              onClick={async () => {
                                try {
                                  setAlarmUpdatingId(alarm.id);
                                  await updateAlarmStatus(alarm.id, "acknowledged");
                                  await loadAlarmItems(currentDeviceCode, alarmStatus);
                                } finally {
                                  setAlarmUpdatingId(null);
                                }
                              }}
                            >
                              确认
                            </button>
                          ) : null}
                          {alarm.status === "acknowledged" ? (
                            <button
                              className="alarm-action-btn"
                              disabled={alarmUpdatingId === alarm.id}
                              onClick={async () => {
                                try {
                                  setAlarmUpdatingId(alarm.id);
                                  await updateAlarmStatus(alarm.id, "resolved");
                                  await loadAlarmItems(currentDeviceCode, alarmStatus);
                                } finally {
                                  setAlarmUpdatingId(null);
                                }
                              }}
                            >
                              解决
                            </button>
                          ) : null}
                          {alarm.status === "resolved" ? <span className="alarm-resolved-tag">已解决</span> : null}
                        </div>
                      ))}
                    </div>
                  ) : null}
                </div>
              </div>
            ) : null}
            {!notFound && !currentDevice ? <div className="status-message">请从列表或关注列表选择设备查看详情。</div> : null}
          </div>
        </div>
      ) : null}
    </div>
  );
}

// frontend/src/pages/DeviceDetailPage.vue
<template>
  <div class="device-page">
    <div class="page-header">
      <button class="back-btn" @click="goBack">返回看板</button>
      <div class="title">设备列表与详情</div>
      <div class="subtitle">搜索、关注并快速进入单设备详情</div>
    </div>

    <div class="filter-bar">
      <input
        v-model.trim="keyword"
        class="filter-input"
        type="text"
        placeholder="搜索设备名称或 deviceCode"
      />
      <select v-model="selectedStatus" class="filter-select">
        <option value="">全部状态</option>
        <option value="normal">normal</option>
        <option value="warning">warning</option>
        <option value="error">error</option>
      </select>
      <button class="clear-btn" @click="clearFilters">清空筛选</button>
      <span class="filter-count"
        >显示 {{ filteredDevices.length }} / {{ allDevicesData.length }}</span
      >
    </div>

    <div v-if="errorMessage" class="status-message error">
      {{ errorMessage }}
    </div>
    <div v-else-if="allDevicesData.length === 0" class="status-message">
      暂无设备数据
    </div>
    <div v-else class="device-layout">
      <div class="list-panel">
        <div class="list-title">设备列表</div>
        <div v-if="filteredDevices.length === 0" class="status-message">
          筛选结果为空，请调整条件
        </div>
        <div
          v-for="device in filteredDevices"
          :key="device.deviceCode"
          class="list-item"
          :class="{ active: currentDevice?.deviceCode === device.deviceCode }"
        >
          <div class="list-item-main" @click="openDevice(device.deviceCode)">
            <div class="name">{{ device.name }}</div>
            <div class="meta">
              {{ device.deviceCode }} · {{ device.status }}
            </div>
          </div>
          <button class="pin-btn" @click="toggleWatch(device.deviceCode)">
            {{ watchSet.has(device.deviceCode) ? "取消关注" : "关注" }}
          </button>
        </div>
      </div>

      <div class="watch-panel">
        <div class="list-title">关注列表</div>
        <div v-if="watchList.length === 0" class="empty-watch">
          暂无关注设备
        </div>
        <div
          v-for="item in watchList"
          :key="item.deviceCode"
          class="watch-item"
          @click="openDevice(item.deviceCode)"
        >
          {{ item.deviceCode }}
        </div>
      </div>

      <div class="detail-panel">
        <div v-if="notFound" class="status-message error">
          未找到设备 {{ route.params.deviceCode }}，请从左侧列表重新选择。
        </div>
        <div v-else-if="currentDevice">
          <div class="detail-with-alarm-actions">
            <DeviceDetailPanel
              :device-data="currentDevice"
              embedded
              @close="goBackToList"
            />
            <div class="alarm-ops-panel">
              <div class="list-title">告警操作（设备列表执行）</div>
              <div class="alarm-tabs">
                <button
                  v-for="tab in alarmTabs"
                  :key="tab.value"
                  class="alarm-tab-btn"
                  :class="{ active: alarmStatus === tab.value }"
                  @click="switchAlarmStatus(tab.value)"
                >
                  {{ tab.label }}
                </button>
              </div>
              <div v-if="alarmErrorMessage" class="status-message error">
                {{ alarmErrorMessage }}
              </div>
              <div v-else-if="alarmLoading" class="status-message">
                告警数据加载中...
              </div>
              <div v-else-if="alarmItems.length === 0" class="status-message">
                当前筛选下暂无告警
              </div>
              <div v-else class="alarm-ops-list">
                <div
                  v-for="alarm in alarmItems"
                  :key="alarm.id"
                  class="alarm-ops-item"
                >
                  <div class="alarm-ops-main">
                    <div class="alarm-ops-event">{{ alarm.event }}</div>
                    <div class="alarm-ops-meta">
                      {{ alarm.time }} · {{ alarm.status }}
                    </div>
                  </div>
                  <button
                    v-if="alarm.status === 'new'"
                    class="alarm-action-btn"
                    :disabled="alarmUpdatingId === alarm.id"
                    @click="applyAlarmStatus(alarm.id, 'acknowledged')"
                  >
                    确认
                  </button>
                  <button
                    v-else-if="alarm.status === 'acknowledged'"
                    class="alarm-action-btn"
                    :disabled="alarmUpdatingId === alarm.id"
                    @click="applyAlarmStatus(alarm.id, 'resolved')"
                  >
                    解决
                  </button>
                  <span v-else class="alarm-resolved-tag">已解决</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div v-else class="status-message">
          请从列表或关注列表选择设备查看详情。
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import DeviceDetailPanel from "@/components/DeviceDetailPanel.vue";
import {
  fetchDevices,
  fetchAlarmList,
  fetchWatchlist,
  pinWatchlistDevice,
  type AlarmListItem,
  type AlarmStatus,
  type DeviceData,
  type WatchlistItem,
  unpinWatchlistDevice,
  updateAlarmStatus,
} from "@/api/backend";

const router = useRouter();
const route = useRoute();
const allDevicesData = ref<DeviceData[]>([]);
const errorMessage = ref<string>("");
const keyword = ref("");
const selectedStatus = ref<"" | DeviceData["status"]>("");
const watchList = ref<WatchlistItem[]>([]);
const currentDeviceCode = ref<string>("");
const alarmItems = ref<AlarmListItem[]>([]);
const alarmStatus = ref<AlarmStatus>("new");
const alarmLoading = ref(false);
const alarmErrorMessage = ref("");
const alarmUpdatingId = ref<number | null>(null);
const alarmTabs: Array<{ label: string; value: AlarmStatus }> = [
  { label: "新告警", value: "new" },
  { label: "已确认", value: "acknowledged" },
  { label: "已解决", value: "resolved" },
];

const watchSet = computed(
  () => new Set(watchList.value.map((item) => item.deviceCode))
);
const currentDevice = computed(() =>
  allDevicesData.value.find(
    (device) => device.deviceCode === currentDeviceCode.value
  )
);
const notFound = computed(
  () =>
    Boolean(currentDeviceCode.value) &&
    !currentDevice.value &&
    allDevicesData.value.length > 0
);

const filteredDevices = computed(() => {
  const normalizedKeyword = keyword.value.toLowerCase();
  return allDevicesData.value.filter((device) => {
    const keywordMatched =
      normalizedKeyword.length === 0 ||
      device.name.toLowerCase().includes(normalizedKeyword) ||
      device.deviceCode.toLowerCase().includes(normalizedKeyword);
    const statusMatched =
      selectedStatus.value === "" || device.status === selectedStatus.value;
    return keywordMatched && statusMatched;
  });
});

const goBack = () => {
  router.push({ name: "dashboard" });
};

const goBackToList = () => {
  router.push({ name: "devices" });
};

const clearFilters = () => {
  keyword.value = "";
  selectedStatus.value = "";
};

const openDevice = (deviceCode: string) => {
  router.push({ name: "device-focus", params: { deviceCode } });
};

const loadWatchlist = async () => {
  watchList.value = await fetchWatchlist();
};

const toggleWatch = async (deviceCode: string) => {
  if (watchSet.value.has(deviceCode)) {
    watchList.value = await unpinWatchlistDevice(deviceCode);
    return;
  }
  watchList.value = await pinWatchlistDevice(deviceCode);
};

const syncRouteState = () => {
  const routeCode =
    typeof route.params.deviceCode === "string" ? route.params.deviceCode : "";
  currentDeviceCode.value = routeCode;
  if (typeof route.query.keyword === "string") {
    keyword.value = route.query.keyword;
  }
};

const loadAlarmItems = async () => {
  if (!currentDeviceCode.value) {
    alarmItems.value = [];
    return;
  }
  try {
    alarmLoading.value = true;
    alarmItems.value = await fetchAlarmList(
      alarmStatus.value,
      20,
      currentDeviceCode.value
    );
    alarmErrorMessage.value = "";
  } catch (error) {
    alarmErrorMessage.value = `告警数据加载失败: ${
      error instanceof Error ? error.message : String(error)
    }`;
  } finally {
    alarmLoading.value = false;
  }
};

const switchAlarmStatus = async (next: AlarmStatus) => {
  if (alarmStatus.value === next || alarmLoading.value) return;
  alarmStatus.value = next;
  await loadAlarmItems();
};

const applyAlarmStatus = async (alarmId: number, nextStatus: AlarmStatus) => {
  try {
    alarmUpdatingId.value = alarmId;
    await updateAlarmStatus(alarmId, nextStatus);
    await loadAlarmItems();
  } catch (error) {
    alarmErrorMessage.value = `告警状态更新失败: ${
      error instanceof Error ? error.message : String(error)
    }`;
  } finally {
    alarmUpdatingId.value = null;
  }
};

watch(
  () => route.params.deviceCode,
  async () => {
    syncRouteState();
    await loadAlarmItems();
  },
  { immediate: true }
);

onMounted(async () => {
  try {
    allDevicesData.value = await fetchDevices();
    await loadWatchlist();
    await loadAlarmItems();
    errorMessage.value = "";
    if (!currentDeviceCode.value && filteredDevices.value.length > 0) {
      currentDeviceCode.value = filteredDevices.value[0].deviceCode;
    }
  } catch (error) {
    errorMessage.value = `设备数据加载失败: ${
      error instanceof Error ? error.message : String(error)
    }`;
  }
});
</script>

<style lang="scss" scoped>
.device-page {
  min-height: 100%;
  height: 100%;
  overflow-y: auto;
  overflow-x: hidden;
  padding: 20px;
  background: radial-gradient(
      circle at 16% 14%,
      rgba(70, 155, 250, 0.2) 0%,
      transparent 38%
    ),
    linear-gradient(
      155deg,
      var(--tw-bg-ink) 0%,
      var(--tw-bg-deep) 52%,
      var(--tw-bg-haze) 100%
    );
}

.page-header {
  display: flex;
  align-items: center;
  grid-gap: 14px;
  margin-bottom: 24px;
}

.filter-bar {
  display: flex;
  align-items: center;
  grid-gap: 10px;
  margin-bottom: 16px;
}

.filter-input {
  width: 260px;
  height: 34px;
  padding: 0 10px;
  color: var(--tw-color-text-on-dark);
  background: rgba(12, 28, 48, 0.8);
  border: 1px solid var(--tw-border-soft);
  border-radius: 8px;
  outline: none;
}

.filter-select {
  height: 34px;
  padding: 0 8px;
  color: var(--tw-color-text-on-dark);
  background: rgba(12, 28, 48, 0.8);
  border: 1px solid var(--tw-border-soft);
  border-radius: 8px;
}

.clear-btn {
  height: 34px;
  padding: 0 12px;
  color: var(--tw-color-text-on-dark);
  cursor: pointer;
  background: linear-gradient(
    120deg,
    var(--tw-cta-start) 0%,
    var(--tw-cta-end) 100%
  );
  border: 1px solid var(--tw-cta-border);
  border-radius: 18px;
}

.filter-count {
  margin-left: auto;
  font-size: 12px;
  color: var(--tw-color-text-on-dark-secondary);
}

.back-btn {
  height: 34px;
  padding: 0 12px;
  color: var(--tw-color-text-on-dark);
  cursor: pointer;
  background: linear-gradient(
    120deg,
    var(--tw-cta-start) 0%,
    var(--tw-cta-end) 100%
  );
  border: 1px solid var(--tw-cta-border);
  border-radius: 18px;
  font-weight: bold;
  box-shadow: var(--tw-cta-shadow);
  transition: all var(--tw-motion-duration-fast) var(--tw-motion-ease-standard);
}

.back-btn:hover {
  transform: translateY(-1px);
  box-shadow: 0 14px 24px rgba(11, 75, 150, 0.56);
}

.title {
  font-family: var(--tw-font-title);
  font-size: 24px;
  color: var(--tw-color-text-primary);
}

.detail-with-alarm-actions {
  display: grid;
  grid-template-columns: 1fr 320px;
  gap: 10px;
}

.alarm-ops-panel {
  border: 1px solid var(--tw-border-soft);
  border-radius: 12px;
  background: rgba(12, 28, 48, 0.82);
  padding: 10px;
}

.alarm-tabs {
  display: flex;
  gap: 6px;
  margin-bottom: 8px;
}

.alarm-tab-btn {
  height: 24px;
  padding: 0 10px;
  font-size: 12px;
  color: var(--tw-color-text-secondary);
  cursor: pointer;
  border: 1px solid var(--tw-border-soft);
  border-radius: 999px;
  background: rgba(10, 25, 46, 0.8);

  &.active {
    color: var(--tw-color-text-on-dark);
    background: linear-gradient(
      120deg,
      var(--tw-cta-start) 0%,
      var(--tw-cta-end) 100%
    );
    border-color: var(--tw-cta-border);
  }
}

.alarm-ops-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.alarm-ops-item {
  border: 1px solid rgba(126, 161, 192, 0.2);
  border-radius: 8px;
  padding: 8px;
  display: flex;
  align-items: center;
  gap: 8px;
}

.alarm-ops-main {
  flex: 1;
}

.alarm-ops-event {
  color: var(--tw-color-text-on-dark);
  font-family: var(--tw-font-body);
  font-size: 13px;
}

.alarm-ops-meta {
  margin-top: 4px;
  color: var(--tw-color-text-secondary);
  font-size: 12px;
  font-family: var(--tw-font-body);
}

.alarm-action-btn {
  height: 26px;
  padding: 0 10px;
  color: var(--tw-color-text-on-dark);
  cursor: pointer;
  border-radius: 999px;
  border: 1px solid var(--tw-cta-border);
  background: linear-gradient(
    120deg,
    var(--tw-cta-start) 0%,
    var(--tw-cta-end) 100%
  );
}

.alarm-resolved-tag {
  font-size: 12px;
  color: #88dca7;
  font-family: var(--tw-font-body);
}

.subtitle {
  font-size: 14px;
  color: var(--tw-color-text-secondary);
}

.device-layout {
  display: grid;
  grid-template-columns: minmax(320px, 28%) minmax(200px, 18%) 1fr;
  align-items: start;
  gap: 14px;
}

.status-message {
  padding: 16px;
  border-radius: 10px;
  color: var(--tw-color-text-on-dark);
  background: var(--tw-status-bg);
  border: 1px solid var(--tw-status-border);
  box-shadow: 0 10px 20px rgba(2, 9, 21, 0.4);
}

.status-message.error {
  color: #ffd2d2;
  background: var(--tw-status-error);
  border-color: rgba(255, 132, 132, 0.44);
}

.device-card-wrapper {
  background: transparent;
  border-radius: 16px;
  overflow: visible;
  display: flex;
}

.list-panel,
.watch-panel,
.detail-panel {
  border: 1px solid var(--tw-border-soft);
  border-radius: 12px;
  background: rgba(12, 28, 48, 0.82);
  padding: 12px;
  min-height: 72vh;
}

.list-title {
  font-weight: 700;
  margin-bottom: 10px;
  color: var(--tw-color-text-on-dark);
}

.list-item {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 8px;
  border: 1px solid rgba(126, 161, 192, 0.2);
  border-radius: 8px;
  padding: 8px;
  margin-bottom: 8px;
}

.list-item.active {
  border-color: rgba(124, 185, 255, 0.9);
  box-shadow: inset 0 0 0 1px rgba(124, 185, 255, 0.34);
}

.list-item-main {
  cursor: pointer;
}

.name {
  color: var(--tw-color-text-on-dark);
  font-weight: 700;
}

.meta {
  margin-top: 4px;
  font-size: 12px;
  color: var(--tw-color-text-on-dark-secondary);
}

.pin-btn {
  height: 28px;
  padding: 0 10px;
  cursor: pointer;
  color: var(--tw-color-text-on-dark);
  border-radius: 14px;
  border: 1px solid var(--tw-cta-border);
  background: linear-gradient(
    120deg,
    var(--tw-cta-start) 0%,
    var(--tw-cta-end) 100%
  );
}

.watch-item {
  border: 1px solid rgba(126, 161, 192, 0.2);
  border-radius: 8px;
  padding: 8px;
  margin-bottom: 8px;
  cursor: pointer;
  color: var(--tw-color-text-on-dark);
}

.empty-watch {
  color: var(--tw-color-text-on-dark-secondary);
  font-size: 13px;
}
</style>
